"""empty message

Revision ID: 17fa3622a0ad
Revises: 51aa98e8f50d
Create Date: 2015-03-15 21:13:37.354416

"""

# revision identifiers, used by Alembic.
revision = '17fa3622a0ad'
down_revision = '51aa98e8f50d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('anatomy_id', sa.Integer(), nullable=True))
    op.add_column('procedures', sa.Column('method_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'procedures', 'groups', ['method_id'], ['id'])
    op.create_foreign_key(None, 'procedures', 'groups', ['anatomy_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_column('procedures', 'method_id')
    op.drop_column('procedures', 'anatomy_id')
    ### end Alembic commands ###
