"""empty message

Revision ID: 1a5d03553c8e
Revises: 2aad38e7314e
Create Date: 2015-03-15 18:40:55.838998

"""

# revision identifiers, used by Alembic.
revision = '1a5d03553c8e'
down_revision = '2aad38e7314e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedure_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_group', sa.Integer(), nullable=True),
    sa.Column('anatomy_group', sa.Integer(), nullable=True),
    sa.Column('show_success', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anatomy_group'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['method_group'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'procedures', sa.Column('comments', sa.String(length=400), nullable=True))
    op.add_column(u'procedures', sa.Column('procedure_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'procedures', 'procedure_types', ['procedure_type'], ['id'])
    op.drop_column(u'procedures', 'attempts')
    op.drop_column(u'procedures', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'procedures', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(u'procedures', sa.Column('attempts', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_column(u'procedures', 'procedure_type')
    op.drop_column(u'procedures', 'comments')
    op.drop_table('group_items')
    op.drop_table('procedure_types')
    op.drop_table('groups')
    ### end Alembic commands ###
