"""empty message

Revision ID: 1d77ec8f3267
Revises: 28da359dad88
Create Date: 2015-10-11 20:19:51.973715

"""

# revision identifiers, used by Alembic.
revision = '1d77ec8f3267'
down_revision = '28da359dad88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retts_codes', sa.Column('type', sa.String(length=16)))
    op.execute('''UPDATE "retts_codes" SET type = 'pediatric' WHERE code > 100''')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retts_codes', 'type')
    ### end Alembic commands ###
