"""empty message

Revision ID: 24b7d43a48ca
Revises: 510d7137376f
Create Date: 2015-03-16 17:27:48.656048

"""

# revision identifiers, used by Alembic.
revision = '24b7d43a48ca'
down_revision = '510d7137376f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retts_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age_id', sa.Integer(), nullable=False),
    sa.Column('triage_id', sa.Integer(), nullable=False),
    sa.Column('retts_id', sa.Integer(), nullable=True),
    sa.Column('admittance', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.String(length=400), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['age_id'], ['group_items.id'], ),
    sa.ForeignKeyConstraint(['retts_id'], ['retts_codes.id'], ),
    sa.ForeignKeyConstraint(['triage_id'], ['group_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
      'UPDATE "group_items" SET weight = 0 WHERE weight is NULL'
      ),
    op.execute(
      'UPDATE "procedure_types" SET weight = 0 WHERE weight is NULL'
      ),
    op.alter_column(u'group_items', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'group_items', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column(u'group_items', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'groups', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column(u'procedure_types', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column(u'procedure_types', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column(u'procedures', sa.Column('tuition', sa.Boolean(), nullable=True))
    op.drop_column(u'procedures', 'user_id')
    op.add_column(u'procedures', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'procedures', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.alter_column(u'procedures', 'user_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column(u'procedures', 'tuition')
    op.alter_column(u'procedure_types', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'procedure_types', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column(u'groups', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column(u'group_items', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'group_items', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column(u'group_items', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('patients')
    op.drop_table('retts_codes')
    op.drop_table('users')
    ### end Alembic commands ###
