"""empty message

Revision ID: 28da359dad88
Revises: None
Create Date: 2015-03-23 22:43:14.804763

"""

# revision identifiers, used by Alembic.
revision = '28da359dad88'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retts_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedure_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('method_group', sa.Integer(), nullable=True),
    sa.Column('anatomy_group', sa.Integer(), nullable=True),
    sa.Column('show_success', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anatomy_group'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['method_group'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('procedure_type', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('anatomy_id', sa.Integer(), nullable=True),
    sa.Column('tuition', sa.Boolean(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['anatomy_id'], ['group_items.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['group_items.id'], ),
    sa.ForeignKeyConstraint(['procedure_type'], ['procedure_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age_id', sa.Integer(), nullable=False),
    sa.Column('triage_id', sa.Integer(), nullable=False),
    sa.Column('retts_id', sa.Integer(), nullable=True),
    sa.Column('admittance', sa.Boolean(), nullable=True),
    sa.Column('tuition', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.String(length=400), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['age_id'], ['group_items.id'], ),
    sa.ForeignKeyConstraint(['retts_id'], ['retts_codes.id'], ),
    sa.ForeignKeyConstraint(['triage_id'], ['group_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    op.drop_table('procedures')
    op.drop_table('procedure_types')
    op.drop_table('group_items')
    op.drop_table('retts_codes')
    op.drop_table('users')
    op.drop_table('groups')
    ### end Alembic commands ###
