"""empty message

Revision ID: 2aad38e7314e
Revises: 7e7882a4d5e
Create Date: 2015-02-15 17:23:29.316792

"""

# revision identifiers, used by Alembic.
revision = '2aad38e7314e'
down_revision = '7e7882a4d5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
