"""empty message

Revision ID: 38b548d22c10
Revises: 24b7d43a48ca
Create Date: 2015-03-17 18:22:10.785521

"""

# revision identifiers, used by Alembic.
revision = '38b548d22c10'
down_revision = '24b7d43a48ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('tuition', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'tuition')
    ### end Alembic commands ###
