"""empty message

Revision ID: 48e01db0ac2f
Revises: 1a5d03553c8e
Create Date: 2015-03-15 18:43:46.267600

"""

# revision identifiers, used by Alembic.
revision = '48e01db0ac2f'
down_revision = '1a5d03553c8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedure_types', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedure_types', 'name')
    ### end Alembic commands ###
