"""empty message

Revision ID: 51aa98e8f50d
Revises: 48e01db0ac2f
Create Date: 2015-03-15 20:08:27.599912

"""

# revision identifiers, used by Alembic.
revision = '51aa98e8f50d'
down_revision = '48e01db0ac2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
