"""empty message

Revision ID: 523dec874608
Revises: 2aad38e7314e
Create Date: 2015-02-28 10:25:29.543741

"""

# revision identifiers, used by Alembic.
revision = '523dec874608'
down_revision = '2aad38e7314e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
