"""empty message

Revision ID: 9ba3a5b62007
Revises: 4b7c65571595
Create Date: 2017-02-26 14:55:39.148892

"""

# revision identifiers, used by Alembic.
revision = '9ba3a5b62007'
down_revision = '4b7c65571595'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residency_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.alter_column(u'roles_users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'roles_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column(u'users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column(u'users', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.add_column(u'users', sa.Column('residency_id', sa.Integer(), nullable=True))

    ### Needs names for the keys for this to work! ###
    op.create_foreign_key('users_department_id_fkey', 'users', 'departments', ['department_id'], ['id'])
    op.create_foreign_key('users_residency_id_fkey', 'users', 'residency_programs', ['residency_id'], ['id'])
    op.create_foreign_key('users_hospital_id_fkey', 'users', 'hospitals', ['hospital_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_department_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_hospital_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_residency_id_fkey', 'users', type_='foreignkey')
    op.drop_column(u'users', 'residency_id')
    op.drop_column(u'users', 'hospital_id')
    op.drop_column(u'users', 'department_id')
    op.alter_column(u'roles_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column(u'roles_users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_table('departments')
    op.drop_table('residency_programs')
    op.drop_table('hospitals')
    ### end Alembic commands ###
